### ISSUE TITLE
[Feature suggestion] Add Dotnet template(s)

### ISSUE THREAD

**Issue by kMutagene** [JaggerJo/Avalonia.FuncUI#10]
Adding dotnet templates for Avalonia.FuncUI will make starting from scratch  easier than copying example files to new projects. 

I would start creating a template from the elmish counter example. This would be consistent with other templates like the [SAFE-Stack template](https://github.com/SAFE-Stack/SAFE-template). 

Should this be included in the main repo (e.g. a `templates` folder in the root of this repo) or be its own project?

**Comment by JaggerJo** [comment]
Hmm, I'd like to keep it as simple as possible. I guess `./templates` or `./src/templates` would be good.

The templates could be also integrated in CI, to make sure they actually work and are up to date.

**Comment by kMutagene** [comment]
I have added the basic template layout in #12 .

**Comment by JaggerJo** [comment]
I’m currently on vacation, will review your PR this weekend. Seems good so far 👍🏼

**Comment by kMutagene** [comment]
No worries, enjoy your vacation!

**Comment by JaggerJo** [comment]
Thanks, I actually had a few minutes and reviewed it. Good job 👍

**Comment by JaggerJo** [comment]
I made some small changes to the template  #13 JaggerJo.Avalonia.FuncUI.Templates

This simplifies packaging multiple templates to one NuGet Package. The NuGet Package is uploaded and should appear in a few minutes.

https://www.nuget.org/packages/JaggerJo.Avalonia.FuncUI.Templates/0.1.0

I will then update the Readme and the Docs.

**Comment by JaggerJo** [comment]
✔ Package is published
✔ Readme is updates
✔ Wiki is updated
