### ISSUE TITLE
A better name

### ISSUE THREAD

**Issue by JaggerJo** [JaggerJo/Avalonia.FuncUI#11]
Fable and Fabulous are great sounding names. FuncUI is ok, but not as great.

If you have suggestions please comment below.

**Comment by kMutagene** [comment]
You could go the way of [FAKE (F# MAKE)](https://fake.build/), using the original name Avalonia and prepend an F for F#: Favalonia. Or like [Fable (F# |> Babel)](https://fable.io/), additionally altering the original name a bit, which could lead to something like Favalanche. Those are the first ideas from the top of my mind. 

Additionally, there are always [Acronym generators](https://acronymify.com/), although some suggestions are not the best suited ones: 
Top scoring suggestion: AFIRE | Avalonia Functional InteRfacE
One of the bad ones: ANUS | Avalonia fuNctional USer 😆

**Comment by JaggerJo** [comment]
Have thought about it for a bit, and think the name is good. It describes really god what the library is about after all.

Also if the library gets extended to other frameworks (WPF, UWP, Xamarin) the name still works great. The prefix can changed accordingly.

I really want to like Fabulous but don’t like how events are abstracted away and how you are still using MVVM constructs (you use command instead of click, ...)
