### ISSUE TITLE
TextInput does not raise events.

### ISSUE THREAD

**Issue by bradphelan** [JaggerJo/Avalonia.FuncUI#16]
I've tried

```
module FooView =
  
    type FooState = {
        text : string
    }

    let initialState = {
        text = "Yo ho ho"
    }

    type FooMsg = 
    | Edit of string

    let update (msg:FooMsg ) (state:FooState) : FooState =
        match msg with
        | Edit text -> { state with text = text}

    let view (state:FooState) (dispatch) : View =
        Views.stackPanel [
            Attrs.children [
                Views.textBox [
                    Attrs.text state.text
                    Attrs.onTextInput(fun sender args -> dispatch (Edit args.Text))
                ]
                Views.textBox [
                    Attrs.text state.text
                ]
            ]
        ]
```

and the two text boxes render and I can add text but the onTextInput never fires. Is this a bug or am I doing something wrong?

**Comment by JaggerJo** [comment]
This is actually a bug in Avalonia itself. With the upcoming release of Avalonia 0.9 and the next version of FuncUI the official way to do this is by subscribing to the observable 'Text' property.

There is a workaround I currently use
```f#
Views.textBox [
    Attrs.onKeyDown (fun obj args ->
        dispatch TextChanged (obj :?> TextBox).Text
    )
    Attrs.onKeyUp (fun obj args ->
        dispatch TextChanged (obj :?> TextBox).Text
    )
]
```

(how it will look in the next version - note that vNext of FuncUI is a complete rewrite and breaking change. Avalonia 0.8 -> 0.9 also has some breaking changes)

![image](https://user-images.githubusercontent.com/13090415/65819901-61dab780-e222-11e9-9a17-8575f8aaa1f9.png)
