### ISSUE TITLE
Is this the correct way to write subviews?

### ISSUE THREAD

**Issue by bradphelan** [JaggerJo/Avalonia.FuncUI#17]
I have a basic view that just ensure that one text box is synchronised with another textbox view the model.

```
module FooView =
  
    type FooState = {
        text : string
    }

    let initialState = {
        text = "Yo ho ho"
    }

    type FooMsg = 
    | Edit of string

    let update (msg:FooMsg ) (state:FooState) : FooState =
        match msg with
        | Edit text -> { state with text = text}

    let view (state:FooState) (dispatch) : View =
        Views.stackPanel [
            Attrs.children [
                Views.textBox [
                    Attrs.text state.text
                    Attrs.onKeyUp(fun sender args -> 
                        dispatch (Edit (sender :?> TextBox).Text) 
                    )
                ]
                Views.textBox [
                    Attrs.text state.text
                ]
            ]
        ]
```

And then my main model has two copies of this 

```
module ParentView =

    // The model holds data that you want to keep track of while the application is running
    type ParentState = {
        foo1 : FooView.FooState
        foo2 : FooView.FooState
    }

    //The initial state of of the application
    let initialState = {
        foo1 = { text = "foo1"}
        foo2 = { text = "foo1"}
    }

    // The Msg type defines what events/actions can occur while the application is running
    // the state of the application changes *only* in reaction to these events
    type CounterMsg =
    | Foo1Msg of FooView.FooMsg
    | Foo2Msg of FooView.FooMsg

    // The update function computes the next state of the application based on the current state and the incoming messages
    let update (msg: CounterMsg) (state: ParentState) : ParentState =
        match msg with
        | Foo1Msg msg -> { state with foo1 = FooView.update msg state.foo1 }
        | Foo2Msg msg -> { state with foo2 = FooView.update msg state.foo2 }
    
    // The view function returns the view of the application depending on its current state. Messages can be passed to the dispatch function.
    let view (state: ParentState) (dispatch): View =
        Views.dockpanel [
            Attrs.children [
                Views.uniformGrid[
                    Attrs.children [
                        FooView.view state.foo1 (Foo1Msg >> dispatch)
                        FooView.view state.foo2 (Foo2Msg >> dispatch)
                    ]
                ]
            ]
        ]       
```
![image](https://user-images.githubusercontent.com/17650/65817763-65af0f80-e20b-11e9-81d8-ed17fc78da96.png)

As this is my first go at FuncUI it feels a bit boilerplatey. Maybe there is a better way to do this but composition of the states and messages into a hierarchy does feel natural. Maybe you can add this example to the readme as a basic example of what to do or not do.

**Comment by JaggerJo** [comment]
Nailed it. That exactly how to do it.

Could you add this to the wiki ? would be great

**Comment by bradphelan** [comment]
I've got a better version for the WIKI. https://gist.github.com/bradphelan/77f3fcb8e660783790c5610290cd8d97

But I'm missing one feature. I've asked the problem on stackoverflow with regards to removing an item from an FSharpX.PersistentVector which doesn't seem possible. Maybe you have a suggestion. FuncUI needs good support from immutable persistent collections APIs.

https://stackoverflow.com/questions/58156504/how-to-remove-an-item-from-index-n-with-fsharpxs-persistentvector

**Comment by JaggerJo** [comment]
Is there a specific reason why you aren't using the builtin FSharpList ? (performance ?)

My way of doing this is actually very similar to yours. I just include something like this in my app and use it where needed.

This is always done on a background thread in my case. Performance was good enough so far without any optimisations.

```fsharp
module List =
    let removeAt (list: 'a list) (index: int) : 'a list =
        list
        |> List.mapi (fun i item ->
            if index = i
            then Some item
            else None  
        )
        |> List.choose id
```

**Comment by bradphelan** [comment]
For sure that is a way to do that. In fact I added a method

```
    let pvDel id = 
        Seq.indexed 
        >> Seq.where ( fun (_id,_)->id<>_id) 
        >> Seq.map (fun (_,p)->p) 
        >> PersistentVector.ofSeq
    type IndexedMessage<'Msg> = ( int*'Msg )
```

To do exactly that but with persistent vector. However there need to be better immutable persistent data structures available to make this scalable for long long lists. It kind of surprises me that the supply of immutable persistent data structures in F# is so limited considering that F# is no longer a new language.

But there seems to be hope on the horizon ( the first comment on my question )

https://stackoverflow.com/questions/58156504/how-to-remove-an-item-from-index-n-with-fsharpxs-persistentvector

**Comment by JaggerJo** [comment]
> However there need to be better immutable persistent data structures available to make this scalable for long long lists. It kind of surprises me that the supply of immutable persistent data structures in F# is so limited considering that F# is no longer a new language.

What exactly are you struggling with ? (How long is your list :D)

**Comment by bradphelan** [comment]
I guess I'm not struggling specifically with anything. Just playing around in some off time. I think the performance problems I've seen are not the model update but the view rendering and virtualisation.
