### ISSUE TITLE
Description for Repo

### ISSUE THREAD

**Issue by 0xaryan** [JaggerJo/Avalonia.FuncUI#4]
Well, this is not a real issue but...
Can you please provide a description for the repo?
![image](https://user-images.githubusercontent.com/9091958/59963923-1459fa80-950f-11e9-945a-522f9ba2ed02.png)

I have an OCD of Good-Repos-should-have-descriptions. 😅

**Comment by JaggerJo** [comment]
![image](https://user-images.githubusercontent.com/13090415/59965604-aca4af00-9510-11e9-94f2-1753197b94bc.png)

Thanks for the hint, added a description (and tags). Let me know if you notice something else 🙂
