### ISSUE TITLE
Project setup guidance

### ISSUE THREAD

**Issue by kMutagene** [JaggerJo/Avalonia.FuncUI#9]
Hi @JaggerJo ,

Very interesting project! While you provide samples, I still feel kinda lost creating a new project from scratch. For example, what program are you using here? Is it required?

![image](https://user-images.githubusercontent.com/21338071/60571743-71a64500-9d74-11e9-9762-215e26d1dfef.png)

Whats the ideal project template to start from? Is it related to the [Avalonia UI .NET core template?](http://avaloniaui.net/docs/quickstart/create-new-project) (e.g. `dotnet new avalonia.app -o MyApp`)

Can you guide me through some basic setup steps? I could do a PR adding the basic steps to your README when i then managed to get a new project running. 

Thanks!

**Comment by JaggerJo** [comment]
Hi @kMutagene!

You are right, it's currently not as easy as it could (and should be) to create a new Project. Templates are planned, but not started yet.

The screenshot features a program of mine created entirely with FuncUI. It's a small 2.5D CAD Application I am building for fun. It's the reason FuncUI was initially created.

> Whats the ideal project template to start from? Is it related to the Avalonia UI .NET core template? (e.g. dotnet new avalonia.app -o MyApp) Can you guide me through some basic setup steps? 

Here is a simple step by step guide:

- create a new .NET Core F# console application (default template)

- add the following NuGet packages
`Avalonia.Desktop`
`JaggerJo.Avalonia.FuncUI`
`JaggerJo.Avalonia.FuncUI.Elmish`

- Copy the following files from the [Counter Example](https://github.com/JaggerJo/Avalonia.FuncUI/tree/master/src/Examples/CounterElmishExample) and adjust the namespaces

Lib.fs
Counter.fs
Main.fs

(this is a bit messy, but Avalonia requires the fat Main class. the names must be like this for the XAML designer to work, so we could theoretically just ignore them as we don't depend on XAML)

if you want to use icons you also need to add this (or a variation of it) to your fsproj file

```xml
<ItemGroup>
    <AvaloniaResource Include="Assets\Icons\*" />    
</ItemGroup>
```

Let me know if you have any further questions or issues.

>  could do a PR adding the basic steps to your README when i then managed to get a new project running.

Would be cool to have this in the Wiki!

**Comment by kMutagene** [comment]
Cool, following your steps it works like a charm!

![image](https://user-images.githubusercontent.com/21338071/60587900-e2118e00-9d95-11e9-8d05-bc173afd29a7.png)

I will have some fun playing around. Is this basic application something you would like to have in the template? If so, i am interested in learning how to build a dotnet template anyways and would volunteer to create a template for the basic elmish counter example if you dont have other plans.

**Comment by kMutagene** [comment]
> Would be cool to have this in the Wiki!

On another note, i have never worked with github wikis before. After some googling i understand now that wikis are separate repos, but so far i only found out how to clone the wiki from the master locally, but i guess then i wont have push rights? Can i somehow fork the wiki to create a PR?

**Comment by JaggerJo** [comment]
> Cool, following your steps it works like a charm!
> 
> I will have some fun playing around. Is this basic application something you would like to have in the template? If so, i am interested in learning how to build a dotnet template anyways and would volunteer to create a template for the basic elmish counter example if you dont have other plans.

That would be great!

My idea was to have like 2 different templates:
- with Elmish.mkSimple (no commands, only messages) and a simple counter
- with Elmish.mkProgram (commands and subscriptions) and simple demo maybe ?

just fork the repo and create a PR when your ready! :)

**Comment by JaggerJo** [comment]
> Would be cool to have this in the Wiki!
> 
> On another note, i have never worked with github wikis before. After some googling i understand now that wikis are separate repos, but so far i only found out how to clone the wiki from the master locally, but i guess then i wont have push rights? Can i somehow fork the wiki to create a PR?

I think you can just edit the Wiki, let me know if you can't :)

**Comment by FoggyFinder** [comment]
> I think you can just edit the Wiki, let me know if you can't :)

> Only repository collaborators can edit a public repository's wiki by default

[Changing access permissions for wikis](https://help.github.com/en/articles/changing-access-permissions-for-wikis)

**Comment by JaggerJo** [comment]
@FoggyFinder thnaks for the tip :) @kMutagene I added you as a collaborator

**Comment by kMutagene** [comment]
@JaggerJo Cool, i added (that is, mainly copied your answer) a from scratch example to the wiki. regarding the templates, I will open a new issue so you/we can track the progress of the template there if thats cool for you
